title: Packages
email: jriguera@users.noreply.github.com
description: >- 
  This is a repository for OS packages
baseurl: "/packages"
url: "https://jose.riguera.es"
github_username: jriguera

# Build settings
theme: jekyll-theme-hacker
plugins: []
exclude:
- incoming