title: Packages
email: jriguera@users.noreply.github.com
description: >- 
  This is a repository for OS packages
baseurl: ""
url: "https://jose.riguera.es/packages/"
github_username: jriguera

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/